<div id="section" class="tig-admin-col-set box">
    <div>
        <span class="globalpack">

            <?= $block->escapeHtml(
                __('Are you planning to ship outside of the EU? ' .
                    'Activate non-EU shipping products with the details you have received from PostNL. ' .
                    'You can ignore the GlobalPack settings for domestic shipping and shipping within the EU.')
); ?>
        </span>
    </div>
</div>

