
<div id="section" class="tig-admin-col-set box <?= $block->escapeHtml($block->getModusClass()); ?>">
    <div class="col col-1">
        <strong><?= $block->escapeHtml(__('Test Mode'));?></strong>
        <p>
            <?php // @codingStandardsIgnoreStart ?>
            <?= __(
    'If you want to test the extension, but do not have any test mode credentials you can request an API key <a href="https://developer.postnl.nl/request-api-key/" target="_blank">here</a>.'
); ?>
            <?php // @codingStandardsIgnoreEnd ?>
        </p>
    </div>
    <div class="col col-2">
        <strong><?= $block->escapeHtml(__('Live Mode'))?></strong>
        <p>
            <?php // @codingStandardsIgnoreStart ?>
            <?= __(
    'In order to use this extension you need to be a contract customer of PostNL. ' .
                'If you are not a customer of PostNL, you can ' .
                '<a href="%1" target="_blank" title="register at PostNL">register yourself here</a>.',
    [$block->getInfoUrlForDeliveryoptions()]
); ?>
            <?php // @codingStandardsIgnoreEnd ?>
            <br><br>
            <?= $block->escapeHtml(__(
                'You will then receive all necessary information in order to configure the extension. If you ' .
                'cannot find the email containing this information, please contact PostNL support at:'
));?>
            <span><a href="https://developer.postnl.nl/support/form/" target="_blank"><?= $block->escapeHtml('https://developer.postnl.nl/support/form/'); ?></a></span>
        </p>
    </div>
</div>
