<input id="time_condition"
       type="hidden"
       name="<?php $block->escapeHtml($block->getTimeConditionName()); ?>"
       value="<?= $block->escapeHtml(time()); ?>">

<script>
    require(['prototype'], function(){
        Event.observe($('carriers_tig_postnl_condition_name'), 'change', checkConditionName.bind(this));
        function checkConditionName(event)
        {
            var conditionNameElement = Event.element(event);
            if (conditionNameElement && conditionNameElement.id) {
                $('time_condition').value = '_' + conditionNameElement.value + '/' + Math.random();
            }
        }
    });
</script>
