<?php /** @var \TIG\PostNL\Block\Adminhtml\Grid\DataProvider $block */ ?>
<script type="text/javascript">
    require([
        'mage/url',
        'TIG_PostNL/js/grid/dataprovider',
        'Magento_Ui/js/grid/toolbar'
    ], function(url, DataProvider) {
        <?php /** @codingStandardsIgnoreStart **/ ?>
        DataProvider.setProductOptions('<?= /* @escapeNotVerified */ $block->getProductOptions();?>');
        DataProvider.setDefaultOption('<?= /* @escapeNotVerified */ $block->getDefaultProductOption();?>');
        DataProvider.setShowToolbar('<?= /* @escapeNotVerified */ $block->getShowToolbar();?>');
        DataProvider.setGuaranteedIsActive('<?= /* @escapeNotVerified */ $block->isGuaranteedDeliveryActive();?>');
        DataProvider.setCargoTimeOptions('<?= /* @escapeNotVerified */ $block->getCargoTimeOptions();?>');
        DataProvider.setPackagesTimeOptions('<?= /* @escapeNotVerified */ $block->getPackagesTimeOptions();?>');
        DataProvider.setInsuredTierOptions('<?= /* @escapeNotVerified */ $block->getInsuredTierOptions();?>');
        DataProvider.setDefaultInsuredTier('<?= /* @escapeNotVerified */ $block->getDefaultInsuredTier();?>');
        DataProvider.setLabelStartPositionOptions('<?= /* @escapeNotVerified */ $block->getLabelStartPositionOptions();?>');
        return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getAdminBaseUrl();?>');
        <?php /** @codingStandardsIgnoreEnd **/ ?>
    })
</script>
