<script type="text/javascript">
    /**
     * This function opens the URL in a new window or tab and refreshes the
     * current page when this tab or window is closed or loses focus.
     *
     * @param downloadUrl
     * @returns {Window}
     */
    function download(downloadUrl)
    {
        var newWindow = window.open(downloadUrl)
        
        var monitorInterval = window.setInterval(function() {
            if(newWindow === null || newWindow.closed || document.hasFocus()) {
                window.location.reload()
                window.clearInterval(monitorInterval)
            }
        }, 500)
        
        return newWindow
    }
</script>
