<?php
/** @var $block TIG\PostNL\Block\Adminhtml\Shipment\Options\View */
?>
<?php if ($block->getIsPostNLOrder()): ?>
<!--@todo move style to less and add style to header trough xml-->
    <style>
        #postnl_shipping_options_selected {
            width: 100%;
            background-color: #efefef;
            margin-top: 1px;
            padding-bottom: 1px;
        }

        .tig_postnl_delivery_info ul {
            padding-top: 10px;
            padding-left: 1rem;
        }

        .tig_postnl_delivery_info ul li {
            margin-bottom: 10px;
        }

        .tig_postnl_delivery_info ul li span.type {
            display: inline-block;
            width: 300px;
            font-weight: 800;
        }

        .tig_postnl_delivery_info ul li .value {
            display: inline-block;
            min-width: 100px;
        }
    </style>

    <?php
    /** @var TIG\PostNL\Model\Shipment $postNLShipment */
    $postNLShipment = $block->getPostNLShipment();
    ?>
    <?php if ($postNLShipment): ?>
    <div id="postnl_shipping_options_selected" data-bind="scope: 'PostNLSelectedOptions'">
        <div class="tig_postnl_delivery_info">
            <ul>
                <li>
                    <span class="type"><?= $block->escapeHtml(__('Product option:')); ?></span>
                    <span class="value option">
                        <?php // @codingStandardsIgnoreStart ?>
                        <?= $block->getProductOptionValue(); ?>
                        <?php // @codingStandardsIgnoreEnd ?>
                    </span>
                </li>
                <li>
                    <span class="type"><?= $block->escapeHtml(__('Ship at:')); ?></span>
                    <span class="value ship_at">
                        <?= $block->escapeHtml($postNLShipment->getShipAt()); ?>
                    </span>
                </li>
                <li>
                    <span class="type"><?= $block->escapeHtml(__('Parcel count:')); ?></span>
                    <span data-bind="visible: !editingParcelCount()">
                        <span class="value parcels">
                            <!-- ko text: parcelCount --><!-- /ko -->
                        </span>
                        <?php if ($block->canChangeParcelCount()): ?>
                        <button
                            class="btn btn-default"
                            data-bind="click: setEditingParcelCount(true)"
                        ><?= $block->escapeHtml(__('Edit')); ?></button>
                        <?php endif; ?>
                    </span>
                    <span data-bind="visible: editingParcelCount">
                        <span class="value parcels">
                            <input type="text" data-bind="value: newParcelCount" class="input-text admin__control-text">

                            <button
                                class="btn btn-default primary"
                                data-bind="click: saveParcelCount"
                            ><?= $block->escapeHtml(__('Save')); ?></button>
                            <button
                                class="btn btn-default"
                                data-bind="click: setEditingParcelCount(false)"
                            ><?= $block->escapeHtml(__('Cancel')); ?></button>
                        </span>
                    </span>
                </li>
            </ul>
        </div>
    </div>

    <!-- Javascript to append the postnl div inside the form elements -->
    <script>
        require([
            "jquery"
        ], function (jQuery) {
            var table = jQuery('#shipment_tracking_info');
            jQuery(function () {
                table.after(jQuery('#postnl_shipping_options_selected'));
            });
        })
    </script>
    <script type="text/x-magento-init">
    {
        "#postnl_shipping_options_selected": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "PostNLSelectedOptions": {
                        "component": "TIG_PostNL/js/shipment/view/options",
                        "parcelCount": "<?= $block->escapeHtml($postNLShipment->getParcelCount()); ?>",
                        "shipmentId": "<?= $block->escapeHtml($postNLShipment->getId()); ?>",
                        "saveUrl": "<?= $block->escapeHtml($block->getUrl('postnl/shipment/SaveMulticolli')); ?>"
                    }
                }
            }
        }
    }
    </script>
    <?php endif; ?>
<?php endif; ?>
