name: Jira issue management

on:
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened

jobs:
  create_issue:
    runs-on: ubuntu-latest
    name: Jira API actions
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Jira API Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: POSTNL
        issuetype: Bug
        summary: |
           [GH] report | ${{ github.event.issue.title }}
        description: |
           Started by: ${{ github.actor }}
           with data: ${{ github.event.issue.body }}
        fields: ${{ secrets.JIRA_FIELDS }}
